### ISSUE TITLE
Pass big numbers as strings

### ISSUE THREAD

**Issue by 0x009922** [soramitsu/iroha2-block-explorer-backend#27]
## Description

At some places we have to deal with 64+ bits integers. We need to extract them from Iroha and pass to frontend via JSON. `serde-json` passes them as numbers to JSON, which is not correct - native `JSON.parse` couldn't handle it properly, and we might lose numbers precision.

Current workaround for it is to use a library like `json-bigint`, which is noted in https://github.com/soramitsu/iroha2-block-explorer-backend/blob/3d0fb37e764d27ce8c5b2b8802645c98e6e57628/api.ts#L86-L98

It is not a great solution for a couple of reasons:

- `json-bigint` and others aren't work on native speed
- external libraries bring overhead

The new solution is to pass big integers as strings. Actually, frontend doesn't always need to decode such data, but when it needs, it can use native `BigInt` or library like `bignumber.js` to work with big integers without precision loss.

This is relevant for big floats as well. `bignumber.js` could handle them properly.

**Comment by antyas** [comment]
related to https://github.com/soramitsu/iroha2-block-explorer-backend/issues/27

**Comment by 0x009922** [comment]
Related: hyperledger/iroha#2716
